In [ ]:
#1. combine.py
import numpy as np

a = np.array([1, 2])

b = np.array([[3, 4],
              [5, 6]])

c = np.vstack((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#2. flatten_reverse.py  
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Flatten Array:")
print(a.flatten())

b = np.array([10, 20, 30, 40, 50])

print("Reverse Array:")
print(b[::-1])

Flatten Array:
[1 2 3 4 5 6]
Reverse Array:
[50 40 30 20 10]


In [4]:

#3. array_operations.py
import numpy as np

a = np.array([[5, 8, 2],
              [10, 3, 7]])

print("Maximum =", np.max(a))
print("Minimum =", np.min(a))

print("Rows =", a.shape[0])
print("Columns =", a.shape[1])

print("First Row =", a[0])

print("Specific Element =", a[1][2])

sum = 0

for i in a:
    for j in i:
        sum = sum + j

print("Sum =", sum)

Maximum = 10
Minimum = 2
Rows = 2
Columns = 3
First Row = [5 8 2]
Specific Element = 7
Sum = 35


In [6]:
#4. arithmetic_operations.py
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 6])

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)

Addition = [12 24 36]
Subtraction = [ 8 16 24]
Multiplication = [ 20  80 180]
Division = [5. 5. 5.]


In [5]:
#5) iterate_3d.py
import numpy as np

a = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Using for loop")

for i in a:
    for j in i:
        for k in j:
            print(k)

print("Using nditer")

for x in np.nditer(a):
    print(x)

Using for loop
1
2
3
4
5
6
7
8
Using nditer
1
2
3
4
5
6
7
8


In [7]:
#6. average_mean_median_mode.py
import numpy as np
from statistics import mode

arr1 = np.array([[3, 4],
                 [5, 6]])

arr2 = np.array([[1, 0],
                 [7, 8]])

avg = (arr1 + arr2) / 2

print("Average Array")
print(avg)

a = np.concatenate((arr1.flatten(),
                    arr2.flatten()))

print("Mean =", np.mean(a))
print("Median =", np.median(a))
print("Mode =", mode(a))

Average Array
[[2. 2.]
 [6. 7.]]
Mean = 4.25
Median = 4.5
Mode = 3
