In [1]:
#1. Create numpy array and print attributes

import numpy as np

a = np.array([10, 20, 30, 40])

print("Array =", a)
print("Shape =", a.shape)
print("Dimension =", a.ndim)
print("Data Type =", a.dtype)
print("Item Size =", a.itemsize)

Array = [10 20 30 40]
Shape = (4,)
Dimension = 1
Data Type = int64
Item Size = 8


In [2]:
#2. Convert 1D array to 2D

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
#3. Create 3x3 NumPy array of all 9

import numpy as np

a = np.full((3, 3), 9)

print(a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [4]:
#4. Create 10 evenly spaced values between 25 and 125

import numpy as np

a = np.linspace(25, 125, 10)

print(a)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [5]:
#5. Convert Python list into NumPy array

import numpy as np

lst = [10, 20, 30, 40]

a = np.array(lst)

print(a)

[10 20 30 40]


In [6]:
#6. Reverse a 1D NumPy array

import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a[::-1])

[5 4 3 2 1]


In [7]:
#7. Create 4x4x3 array and extract value at second set,
#first row and last column

import numpy as np

a = np.arange(48).reshape(4, 4, 3)

print(a)

print("Required Value =", a[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
Required Value = 14


In [8]:
#8. Create 4x4 array and extract odd rows and even columns

import numpy as np

a = np.arange(1, 17).reshape(4, 4)

print(a)

print(a[::2, 1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4]
 [10 12]]


In [9]:
#9. Slice first two rows and first two columns
#of second set from 4x4x3 array

import numpy as np

a = np.arange(48).reshape(4, 4, 3)

print(a[1, :2, :2])

[[12 13]
 [15 16]]


In [10]:
#10. Replace odd numbers with -1 using for loop

import numpy as np

a = np.array([[23, 56, 78, 93],
              [71, 82, 13, 24]])

for i in range(len(a)):
    for j in range(len(a[i])):
        if a[i][j] % 2 != 0:
            a[i][j] = -1

print(a)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [11]:
#11. Get indices of non-zero elements

import numpy as np

a = np.array([1, 0, 2, 0, 3, 0, 4])

print(np.nonzero(a))

(array([0, 2, 4, 6]),)


In [12]:
#12. Perform arithmetic operations on two arrays

import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 6])

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)

Addition = [12 24 36]
Subtraction = [ 8 16 24]
Multiplication = [ 20  80 180]
Division = [5. 5. 5.]


In [13]:
#13. Add two NumPy arrays element by element

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [14]:
#14. Multiply two NumPy arrays element by element

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b)

[ 4 10 18]


In [15]:
#15. Compute dot product of two NumPy arrays

import numpy as np

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot = np.dot(arr1, arr2)

print("Dot Product =", dot)

Dot Product = 1875
